version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bootcamp
      POSTGRES_USER: bootcamp
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
